### ISSUE TITLE
Unity sound not working after close webview.

### ISSUE THREAD

**Issue by Changsoo-UTop** [gree/unity-webview#1079]
Hello. I'm using gree webview for showing Youtube or web E-book contents and It worked great until Android 13.
but I tested in Android 14, It worked something weird.

1. Play background music in Unity.
2. Open webview with Youtube URL or internal E-book contents on Unity.
3. Do some interaction to play sound. (Touch unmute button on Youtube web page or touch speaker button for narration on E-Book contents.)
4. Close webview.
5. Unity sound is not work. (But It's playing. just can't hearing.)

What can I do for fix this bug?

Thank you.

**Comment by Changsoo-UTop** [comment]
It only happens in Android 14.

**Comment by KojiNakamaru** [comment]
Based on the sample app, could you please provide a minum project that reproduces the issue? You can attach a zip file here.

**Comment by Changsoo-UTop** [comment]
[APK.zip](https://github.com/user-attachments/files/16022976/APK.zip)

Thank you for reply!
Here is an APK that can reproduce the issue.

**Comment by Changsoo-UTop** [comment]
[SampleProject.zip](https://github.com/user-attachments/files/16022986/SampleProject.zip)

And this is I made project to make that APK.

Unity version: 2022.3.31f1
Build: macOS Sonoma 14.5

**Comment by Changsoo-UTop** [comment]
https://github.com/gree/unity-webview/assets/100737974/bb7494a4-3d80-4341-b4a2-6899d5dc295e

Here is a video.

Device: Samsung Galaxy Z Flip 5

**Comment by KojiNakamaru** [comment]
Thank you for the archives and the movie. I was able to reproduce the issue on my devices; one was Headwolf FPad5 (Android 14) and another was OSCAL Pad8 (Android 11).

* With Unity 2022.3.31f1,
  * the issue occured on both devices.
  * the issue didn't occur if "Other Settings/Configuration/Mute Other Audio Sources" was turned off.
* With Unity 2021.3.11f1,
  * the issue didn't occur.

As you mentioned, the cause seems to be related to Audio Focus, but it doesn't depend on Android versions, instead, it depends on Unity versions. The easiest workaround is to turn "Other Settings/Configuration/Mute Other Audio Sources" off.

**Comment by Changsoo-UTop** [comment]
Oh.. I didn't thought test with "Mute Other Audio Sources"...
Thank you for so much for testing and answer!
