### ISSUE TITLE
WEB AR service in ARGlass

### ISSUE THREAD

**Issue by Yoon0yoon** [gree/unity-webview#1124]
Hello

I am developing a WEB AR service.

I want to run it on AR Glass, but it crashes.
I use Diglens-ARGO.
https://www.digilens.com/argo/

It works fine on Android smartphone, but on AR Glass, the renderer process crashes within 20 seconds. Can you give me some advice on this?

![image](https://github.com/user-attachments/assets/1afdae25-7d53-4bcb-96b9-3f6c2269a1b3)

**Comment by KojiNakamaru** [comment]
The webview component might be embedded and could not be updated as on ordinal Android devices.

You can try to create a minimum sample app that displays https://google.com as I saw http instead of https causes this error somewhere before. If it still causes the same error, you can provide the sample app digilens to ask to investigate the issue.
