### ISSUE TITLE
Not working on Unity 5.6

### ISSUE THREAD

**Issue by juannibanez** [gree/unity-webview#154]
Hi, this version of unitywebview is not displayed on the lastest version of unity (5.6.0f3). 
Is there a way I can fix that? Thanks

**Comment by KojiNakamaru** [comment]
It seems to run without any error as below (on OS X El Capitan). Without `-force-metal` I guess Unity 5.6.0f3 still runs on OpenGL and should not cause any error.

![image](https://cloud.githubusercontent.com/assets/2645978/24686388/97de7d48-19ee-11e7-8f93-249d7174e435.png)

**Comment by juannibanez** [comment]
Hi, thanks for answering! Here is a screenshot of what is happening when building for android. The page seems to appear transparent and then it disappear. 

![capturapantalla1](https://cloud.githubusercontent.com/assets/19873892/24706532/6d70d04a-19e6-11e7-8016-9fb56c3d63e1.PNG)
![capturapantalla3](https://cloud.githubusercontent.com/assets/19873892/24706541/743ef956-19e6-11e7-9d60-3133b5384c84.PNG)
![capturapantalla2](https://cloud.githubusercontent.com/assets/19873892/24706551/7dc44a6c-19e6-11e7-8caf-f001d6b6a213.PNG)

**Comment by QaisAlkhateeb** [comment]
I have the same Issue in Unity 5.6

**Comment by KojiNakamaru** [comment]
Thanks, I've also confirmed the issue. I'm trying to find a solution but it may take long. The googleads-mobile-unity (cf. https://github.com/googleads/googleads-mobile-unity/commit/607bd756dc39ca5bc218d16a24c2d43f9a71faad ), for example, utilizes PopupWindow without the 'focusable' flag to avoid the issue, but this approach is not applicable for this plugin because we need focus/keyboard inputs.

**Comment by KojiNakamaru** [comment]
Okay, I've fixed the issue: https://github.com/gree/unity-webview/pull/155 . Could you please try the latest.

**Comment by QaisAlkhateeb** [comment]
Hi, thank you 
I'm working in android and I test the latest edits and it's work 
thank you again

**Comment by KojiNakamaru** [comment]
:-)
