### ISSUE TITLE
About issue in Android with Unity 5.6.x

### ISSUE THREAD

**Issue by lchout** [gree/unity-webview#163]
Hello,

About the issue of the webview not showing up in Android with Unity 5.6.x you said: "Please refer plugins/Android/src/net/gree/unitywebview/CUnityPlayerActivity.java and plugins/Android/src/net/gree/unitywebview/CUnityPlayer.java if you already have your own acitivity implementation."

I don't  understand what it means. I have only a activity called "MainActivity" so what am I suposed to do?

**Comment by KojiNakamaru** [comment]
If you have your own activity, it should be derived from `com.unity3d.player.UnityPlayerActivity`. For Unity 5.6, you need to adjust your activity so that it instantiates a custom view derived from `com.unity3d.player.UnityPlayer` and set it as a content view. The custom content view will then call `SurfaceView#setZOrderOnTop(false)` before adding the Unity's `SurfaceView`.

CUnityPlayerActivity.java and CUnityPlayer.java minimally implements the above logic and are very short. Please adjust your `MainActivity` by consulting them:

* https://github.com/gree/unity-webview/blob/8b5f7f88c5ee683d6fc74d0fb81edb3f539d80fd/plugins/Android/src/net/gree/unitywebview/CUnityPlayerActivity.java
* https://github.com/gree/unity-webview/blob/8b5f7f88c5ee683d6fc74d0fb81edb3f539d80fd/plugins/Android/src/net/gree/unitywebview/CUnityPlayer.java
