### ISSUE TITLE
changing webview background color

### ISSUE THREAD

**Issue by jose-castillo** [gree/unity-webview#183]
I implemented it on an older version of your plugin customized for Unity 5.2.1f1

**Comment by KojiNakamaru** [comment]
The current version allows to make a webview transparent. You can then specify any background color in html/javascript.

**Comment by jose-castillo** [comment]
yes, this is possible to do, but if you want the webview to start with that color, it is not the best solution. it would be nice to have it instead of transparent, to set the color by ourselves if possible.

**Comment by KojiNakamaru** [comment]
You can utilize EvaluateJS() to change the color at start. Controlling the background color in html is also better than controlling it with C#, because you can hand off it to designers. Basically I don't want to extend the code if a problem can be solved with the existing APIs and small efforts.

You can of course add your SetBackgroundColor() method to WebViewObject and/or its derived class, in which you call EvaluateJS() to change the background color.

**Comment by jose-castillo** [comment]
Thanks, this was helpful.
