### ISSUE TITLE
Unity.call overrides previous Unity.call

### ISSUE THREAD

**Issue by whimsica** [gree/unity-webview#189]
In javascript:

Unity.call("message1");
Unity.call("message2);

only message2 is processed.
How can I get both messages to be processed?

I'm using mac editor and wkwebkit

**Comment by KojiNakamaru** [comment]
I've modified the definition of `Unity.call()` in https://github.com/gree/unity-webview/issues/149#issuecomment-285857755 . The new definition solves the issue discussed but it has the side effect you described. If the following original definition based on `iframe` works well for you, please utilize it:

```c#
                webViewObject.EvaluateJS(@"
                  window.Unity = {
                    call: function(msg) {
                      var iframe = document.createElement('IFRAME');
                      iframe.setAttribute('src', 'unity:' + msg);
                      document.documentElement.appendChild(iframe);
                      iframe.parentNode.removeChild(iframe);
                      iframe = null;
                    }
                  }
                ");
```

If you only need to support WKWebView and not UIWebView, you can also utilize the WKWebView's scriptMessageHandler, which is more reliable. Instead of `Unity.call()` you can call `window.webkit.messageHandlers.unityControl.postMessage()`.

**Comment by whimsica** [comment]
Thanks the iframe method seems to work fine.

I only need to support WKWebView but would be interested in the MessageHandler to see if there is any speed difference.

I tried calling
window.webkit.messageHandlers.unityControl.postMessage('some message').

**Comment by KojiNakamaru** [comment]
Yes, it is implemented. Please note that even if you specify `enableWKWebView: true` it might become undefined because the plugin falls back to UIWebView if the target iOS doesn't support WKWebView.

**Comment by whimsica** [comment]
I'm trying it in the unity editor on a mac. Is that why it would be undefined?

If I call 
window.webkit.messageHandlers.unityControl.postMessage('someMessage');
do I have to create a function in the sampleWebView named unityControl to receive the string?

**Comment by KojiNakamaru** [comment]
Ah, sorry, it is only implemented for the iOS version. It should work on iOS devices.

**Comment by whimsica** [comment]
The webkit method is much faster in my tests. Thanks.
