### ISSUE TITLE
apk build by Unity 2017.1.0f3 crash.

### ISSUE THREAD

**Issue by Ellisonlee** [gree/unity-webview#222]
The apk crashed when started by error 

> java.lang.NoSuchMethodError: com.unity3d.player.UnityPlayer.<init>

**Comment by KojiNakamaru** [comment]
At least the sample app seems to run well on Nexus 7 (2017)/Android 6.0.1.

**Comment by Ellisonlee** [comment]
try to work with the latest plugin. thx.

**Comment by KojiNakamaru** [comment]
Of course I utilize the latest plugin and it works without any issue.

**Comment by mhozumi** [comment]
I had a same problem.

I changed CUnityPlayer.java from 
`public CUnityPlayer(ContextWrapper contextwrapper) `
to
`public CUnityPlayer(Context contextwrapper)`

Because, the constructor of Unity 2017's classes.jar is `public UnityPlayer(Context context). `

*I add dependences in build.gradle. 
`provided files  ({Unity2017 Directory}/Editor/Data/PlaybackEngines/AndroidPlayer/Variations/mono/Release/Classes/classes.jar')`

**Comment by KojiNakamaru** [comment]
You don't need to utilize custom CUnityPlayer.java anymore.
cf. https://github.com/gree/unity-webview#android
cf. https://github.com/gree/unity-webview/issues/221#issuecomment-316298147
cf. https://github.com/gree/unity-webview/pull/212#issuecomment-314952793
