### ISSUE TITLE
Cannot type in an inline javascript editor called EditArea

### ISSUE THREAD

**Issue by whimsica** [gree/unity-webview#255]
For some reason the unity-webview will not let me type in EditArea -- an html javascript editor like the Ace editor but older. No keystrokes are received in the unity editor or the iphone while running this particular page: 

[](http://www.cinematicsciences.com/editareatest.html)

I was wondering if you had any ideas about how to troubleshoot it. I think how it works is that there is a textarea and a div in an iframe. The textarea receives the typing and the program draws on top of the textarea to color it and make it look nice. I'm not sure why this would be a problem for unity webview.

I'd greatly appreciate any troubleshooting suggestions.

**Comment by KojiNakamaru** [comment]
The implementation for UNITY_EDITOR/UNITY_STANDALONE_OSX currently feeds an off-screen WebView pseudo keyboard/mouse events. Because it isn't an ordinal visible view, it behaves differently. I'm trying to reduce the issue but it may take time... 

On the other hand, Android/iOS implementations and WebView_Separated (https://github.com/gree/unity-webview/tree/7c61559e3ad8e01d858c8658840d38d193efccd3#webviewseparatedbundle) don't have this issue.

**Comment by whimsica** [comment]
Thanks for looking into this.  I tried an IOS build and it behaves exactly the same as the editor. I haven't seen any other pages that don't work besides that one. I think the problem is primarily with that editor and not a problem with unity-webview, but have no idea why only that page would have a problem.

**Comment by KojiNakamaru** [comment]
At least the sample app works well for 
http://www.cdolivet.com/editarea/editarea/exemples/exemple_full.html as below.
![image](https://user-images.githubusercontent.com/2645978/31415571-35b4e99e-ae5f-11e7-91e2-15b6f992df7b.png)
I'm using Unity 5.5.4f1.

**Comment by whimsica** [comment]
I've tested it in unity 2017 and it's also working in ios. Also the monopinvokecallback version is also working Thanks for looking into this for me.
