### ISSUE TITLE
webview opened from two different browser in Android

### ISSUE THREAD

**Issue by lutfianasari** [gree/unity-webview#258]
I don't know if it only happens on some android (i tested using Xiaomi Redmi 4), 
I want to open an html page on my server with GET request. I added a token key in the header using `webViewObject.AddCustomHeader("Authorization", "Bearer ....");` 
Sometimes, it can go as it has to be, but sometimes (I don't know, maybe the timing is not good?) the token is not there, and therefore the server reject the request.

I checked the request log in my server, and it seems that there are two kinds of GET requests there with different request agent.
"HTTP_USER_AGENT"=>"Mozilla/5.0 (Linux; Android 6.0.1; Redmi 4 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36"
--> With this agent, the token is not there.

"HTTP_USER_AGENT"=>"Dalvik/2.1.0 (Linux; U; Android 6.0.1; Redmi 4 MIUI/V8.0.5.0.0.MBECNDG)"
--> With this agent, the token is there

Is there a way to choose which browser we want to use?

In POST request, by the way, the behavior is a little bit different.
When it supposed to do only POST, it does a GET request, and then POST request after that.
Is it the android webview problem? because I saw some similar issues in StackOverFlow.

**Comment by kira1928** [comment]
The original user-agent (made by webview) is different with the custom-header-request's user-agent([made by HttpURLConnection](https://github.com/gree/unity-webview/blob/13d2329e4f4135fa7eb69a29cd11782f6cf9fd33/plugins/Android/src/net/gree/unitywebview/CWebViewPlugin.java#L148)), which means that you will lost all your original request headers if you use custom-header in unity-webview.

Sometimes, for example when the server returned a 404 response code, unity-webview will send both original request and custom-header-request, so you can find 2 different user-agents in server log. I think it's a bug in unity-webview.

In POST request, in order to add custom header, unity-webview will block the original request, and then made a default `HttpURLConnection` **GET** request instead. So I think it's also a unity-webview bug.

It's very complex and unreliable to fix the second bug in api level < 21, but if your min-sdk is >= 21, then you can use a <a href="https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldInterceptRequest(android.webkit.WebView, android.webkit.WebResourceRequest)">modern api</a> to fix those problems in unity-webview source code.

**Comment by KojiNakamaru** [comment]
I'm sorry that I couldn't respond quickly. @kira1928 Thanks for your detailed analysis. @lutfianasari I put an experimental fix #259. Though I haven't tested it yet, could you please try that?

**Comment by lutfianasari** [comment]
@KojiNakamaru Thank you very much for your response. I will try that and give the result here soon.

**Comment by lutfianasari** [comment]
@KojiNakamaru Very sorry for my late report. It seems that it didn't solve the issue. The behavior is still the same. I put the access token as a parameter when accessing the url so that it doesn't get rejected (not a very good way  though). 
I don't know which agent, but sometimes it makes the OnApplicationPause run. It seems that one of the agent is considered as different app, so when it is called, the OnApplicationPause works.

**Comment by KojiNakamaru** [comment]
Thanks for the report. I updated https://github.com/gree/unity-webview/pull/259 in which I set the UA directly to the HttpURLConnection. I again haven't tried it by myself (sorry), but could you please try it again?

**Comment by lutfianasari** [comment]
Really appreciate your update. I will try that and give report again here as soon as I can.
However, I'm afraid it will be a bit take times because of some other works.
Btw, do you think this issue is due to the use of AddCustomHeader method?

**Comment by lutfianasari** [comment]
I tried it just know. It still didn't solve the issue and has warning:

> A WebView method was called on thread 'Thread-7060'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {9d4e7f8} called on null, FYI main Looper is Looper (main, tid 1) {9d4e7f8})
>                                                              at android.webkit.WebView.checkThread(WebView.java:2292)
>                                                              at android.webkit.WebView.getSettings(WebView.java:1889)
>                                                              at net.gree.unitywebview.CWebViewPlugin$1$1.shouldInterceptRequest(CWebViewPlugin.java:151)
>                                                              at android.webkit.WebViewClient.shouldInterceptRequest(WebViewClient.java:155)
>                                                              at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:52)
>                                                              at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:9)
>                                                              at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:11)

**Comment by KojiNakamaru** [comment]
Yes, as analyzed by @kira1928 `AddCustomHeader()` leads another connection with `HttpURLConnection` and its default UA differs from that of `WebView`. I originally tried to set the same UA through `System.setProperty("http.agent", ...)` but it seemed not working as you tested. I found another article which utilized `URLConnection.setRequestProperty()` instead of `System.setProperty("http.agent", ...)` because the latter didn't work, so updated #259.

**Comment by KojiNakamaru** [comment]
@lutfianasari Thank you for trying. I'll check the issue about threading and also about the original UA issue.

**Comment by KojiNakamaru** [comment]
@lutfianasari I've updated the code:
https://github.com/gree/unity-webview/pull/259/commits/10cb8380249971f80964844e6e8d56350d1ef992
and the binaries:
https://github.com/gree/unity-webview/pull/259/commits/faf98de996369467025bdca63588871439d1d6a3
I briefly tested it and it seemed working. Could you please give it another try? Thanks in advance.

**Comment by lutfianasari** [comment]
Really sorry for my late response. I tested it and had a little bit confusing here.
By using the master branch version, the behavior I described in the beginning appears less frequently than using this updated version. 
My problem is (beside the problem of server rejecting the request), sometimes `OnApplicationPause(false)` run when I move from a webview page to another webview page (both pages are on the server). I'm sorry for not explaining that the behavior I described on the beginning happened when I move from a webview page to another webview page.

Did you try POST request too?

**Comment by KojiNakamaru** [comment]
Ah, the implementation of custom headers doesn't work well for POST on Android...

https://github.com/gree/unity-webview/blob/faf98de996369467025bdca63588871439d1d6a3/plugins/Android/src/net/gree/unitywebview/CWebViewPlugin.java#L143

This method isn't provided any argument to detect whether a request is GET or POST. Though another variation of the method was added and with it we can detect the request type, it only works for API 21/Android 5.0 or later (and also has another limitation (cf. https://github.com/KonstantinSchubert/request_data_webviewclient ). This issue seems to be discussed repeatedly and solutions are very tricky...

https://stackoverflow.com/questions/13954049/intercept-post-requests-in-a-webview
https://stackoverflow.com/questions/13237347/android-check-if-request-is-get-or-post

If possible, it is better to simply utilize GET instead of POST. Normally GET should work for relatively large data:

https://stackoverflow.com/questions/13954049/intercept-post-requests-in-a-webview/13961040#13961040

About the `OnApplicationPause(false)` issue, the implementation checks `url` to be loaded as below:

https://github.com/gree/unity-webview/blob/faf98de996369467025bdca63588871439d1d6a3/plugins/Android/src/net/gree/unitywebview/CWebViewPlugin.java#L172-L187

so any redirection may happen for some url with protocol other than `http://`, `https://`, `file://`, 'javascript:', 'unity:' and cause `view.getContext().startActivity(intent)` at the end.

**Comment by lutfianasari** [comment]
I'm sorry for not responding for a while.
Is my test right?
using the latest version of this branch, the user agent becomes `"HTTP_USER_AGENT"=>"Mozilla/5.0 (Linux; Android 6.0.1; Redmi 4 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36"` (in my case).
--> the token was not here with the master branch, but it is here now with this version

so, will the user agent always be the same now?

I have to use POST from webview, and it is difficult to change. I will try another way to POST it.
I think the problem is related to the request behavior of android (until it find stable connection(?), sometimes it does multiple request).

Thanks for the explanation about `OnApplicationPause(false)` 👍

**Comment by KojiNakamaru** [comment]
> so, will the user agent always be the same now?

Yes, with the HEAD of this branch the user agent should always be the same (though the issue of POST remains). I'll merge it to the master later.
