### ISSUE TITLE
Can I do some action in unity when webview is open?

### ISSUE THREAD

**Issue by Ghoulversi** [gree/unity-webview#330]
Can I check if a person press button on webview to do action in unity?

**Comment by KojiNakamaru** [comment]
As the sample app does in the following:
https://github.com/gree/unity-webview/blob/542fbf4616f0d3231bf18d8a63f17294b2bc8069/sample/Assets/StreamingAssets/sample.html#L15
you can send a string to the unity side by `Unity.call()`. Therefore you can add it to buttons you want to check so that you can detect which button is pushed.

**Comment by Ghoulversi** [comment]
Thanks
