### ISSUE TITLE
Android One middle-end phone slow perfomance (resolved issue with Unity 2017 resetting hardwareAccelerated to false in the build process)

### ISSUE THREAD

**Issue by idchlife** [gree/unity-webview#382]
Hello! Thank you very much for this fantastic project!

I was wondering, is there way to up the performance on now high-end devices?

Using Nokia 6.1 32GB for testing purpose.

Also, input file not working but I read somewhere here that it can be broken on some Android devices.

**Comment by KojiNakamaru** [comment]
Could you please check https://github.com/gree/unity-webview#hardwareaccelerated for achieving a good performance? The implementation should automatically perform the required adjustment for AndroidManifest.xml and you should get a good performance at least after the second build. If you still feel that the webview is slow compared with the ordinal chrome browser, the implementation might fail to perform the adjustment because of some unknown bugs... Anyway, I think it is valuable to check https://github.com/gree/unity-webview#hardwareaccelerated if you haven't yet.

About "input file", I've implemented it once but put it experimental, because it cannot work for some devices as you described: https://github.com/gree/unity-webview/pull/77 .

**Comment by idchlife** [comment]
@KojiNakamaru 

If I'm not mistaken acceleration is turned on. I tested also on Samsung s7, Samsung s8, Samsung s9, every device webview is very slow :(

<img width="1439" alt="default" src="https://user-images.githubusercontent.com/4563032/49805707-d9f4f100-fd66-11e8-9d52-16a688cbad28.png">

**Comment by idchlife** [comment]
@KojiNakamaru I can't understand if this does show something, but when I export project from Unity, Android project, there is AndroidManifest.xml and it has hardwareAcceleration="false", despite manifest file in the Plugins/Android plugin having "true".

I tested Unity build with Samsung s7, s8, s9, all of the phones having very slow performance. s7 even freezes and starts to heat the phone

**Comment by idchlife** [comment]
I discovered that I am able to build in Unity 2017 with hardwareAccelerated=true by exporting Android project (Unty -> build -> android -> checkbox export -> choose folder), opening exported folder with Android Studio, changing hardwareAccelerated to true in AndroidManifext.xml and building project from Android Studio.

After that it worked flawlessly!

I hope it helps everyone who stumbled across this issue.
