### ISSUE TITLE
callback is not returned when you run the actual machine of iOS

### ISSUE THREAD

**Issue by st0326s** [gree/unity-webview#45]
I am not sorry to ask questions in a row

It did not come in place of a call back when you run in iphone actual equipment.

Normally callback was returned in on Unity editor.

We tried to determine the cause

**WebView.mm** of

```
gameObjectName = [NSString stringWithUTF8String: gameObjectName_];
```

It was like a cause in which the object name is not set correctly at the.

If you change as described below, we were able to get the correct object name.

```
// gameObjectName = [NSString stringWithUTF8String: gameObjectName_];
    
     gameObjectName = [[NSString alloc] initWithUTF8String: gameObjectName_];
```

You think I can get successfully object name in those of the author like?

*****  Enviroment *****
iOS8.4 
iPhone5S
Xcode6.4

**Comment by KojiNakamaru** [comment]
Hmm, strange. I've fixed WebView.mm about ARC in https://github.com/gree/unity-webview/pull/40 and the latest `sample/` works without any modification even for iOS. My environment is:
Unity 5.1.3p1
Xcode 6.4
iPad3/iOS8.4.1

**Comment by st0326s** [comment]
Well, there are things to be worried about.
So it did not pass build a version of last week you have to build and remove the ARC of WebView.mm.

It sets the following flag and I are building, but whether it's better you do not want to set?

-fno-objc-arc

**Comment by KojiNakamaru** [comment]
Yes, for any version before https://github.com/gree/unity-webview/pull/40 `-fno-objc-arc` was required for recent Unity 5, which enables ARC for its emitted Xcode project by default. I thought setting `-fno-objc-arc` was a bit tedious step and thus fixed WebView.mm.

Another way is to build a library of the previous `WebView.mm` as `libWebView.a` with `-fno-objc-arc` and put it under `Plugins/iOS` instead of `WebView.mm`. If you want to use previous one, this approach might be useful.

**Comment by st0326s** [comment]
Thanks you,
Those problems, it was resolved.

We were able to receive a call bank in the actual equipment.


Thank you tell me to how to call in a library.
