### ISSUE TITLE
To view the Unity screen of the front than WebView?

### ISSUE THREAD

**Issue by st0326s** [gree/unity-webview#48]
Currently, using the margin of WebView Displaying Unity of parts and WebView at the same time, please tell me whether the following is possible

1.
If you were to view the WebView,
Always Will it be displayed in the front than the Unity?

2.
Is it possible to be displayed in the front than the WebView the Unity of the button?

Nice to meet you.

**Comment by KojiNakamaru** [comment]
> 1.
> If you were to view the WebView,
> Always Will it be displayed in the front than the Unity?

Yes.

> 2.
> Is it possible to be displayed in the front than the WebView the Unity of the button?

I guess you would like to display unity's rendering (such as uGUI buttons) over webview, and if it is corrent, the answer is no. Because a webview is a separate view overlayed on the top of the unity's view, buttons rendered by unity cannot be overlayed on webview. Such an implementation could be possible but requires a lot of work and also lean to cause performance issues.

**Comment by st0326s** [comment]
Thanks for your answer.
It was very helpful because I wanted you to know can how far things
