### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by cosmicmosmic** [gree/unity-webview#543]
First of all, I apologize for leaving a message because I couldn't understand it because of my poor skills.

We recently received a new version of the app store to address the following warnings. 
...ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as...

What I understand is that...
I just deleted file "WebViewWithUIWebView.mm"
and 
add client code with argument "true" webViewObject.Init(enableWKWebView: true);

But the appstore keeps issuing the same warning. (ITMS-90809: Deprecated API Usage)

Our game is only available with iOS 10 or higher.

If my method is wrong, can you tell me how to solve it?

Thank you always,

**Comment by KojiNakamaru** [comment]
Yes, your understanding is correct. Furthermore, you don't have to delete WebViewWithUIWebView.mm if the target iOS version is 9.0 or later, as WebView.mm and WebViewWithUIWebView.mm contains `#if` directive for iOS versions.

The problem is perhaps caused by the Unity version you use and/or any other third-party plugins (many old ads plugins have references to UIWebView). About the Unity version, could you please check https://issuetracker.unity3d.com/issues/ios-apple-throws-deprecated-api-usage-warning-for-using-uiwebview-when-submitting-builds-to-the-app-store-connect . I've also added this link in README.md.

**Comment by cosmicmosmic** [comment]
Thank you for your reply.
Currently, we are using Unity version 2017.4.35f
I will look for other third-party plugins that use UIWebView.
