### ISSUE TITLE
Can't open with null link html.

### ISSUE THREAD

**Issue by iletai** [gree/unity-webview#595]
I had facing issues when trying to open a share button in the same link (https://developers.facebook.com/docs/plugins/share-button/) on the website. Webview stuck and do nothing return, but only platform ios have issues, android still success. 
And error return: CallOnError[Error Domain=NSURLErrorDomain Code=-999 "(null)".

**Comment by KojiNakamaru** [comment]
I'm sorry for this slow reply. The cause is that the facebook share button requires another window to be opened by specifying `target="_blank"`, which is currently not supported by this plugin. There is, however, an experimental implementation #388 that allows one extra window open. Replacing Assets/Plugins/iOS/WebView.mm with this experimental implementation https://github.com/gree/unity-webview/blob/38458bce76b16fb2ca286d34a606f4f35f2a5c6b/plugins/iOS/WebView.mm could solve the issue.

**Comment by iletai** [comment]
> I'm sorry for this slow reply. The cause is that the facebook share button requires another window to be opened by specifying `target="_blank"`, which is currently not supported by this plugin. There is, however, an experimental implementation #388 that allows one extra window open. Replacing Assets/Plugins/iOS/WebView.mm with this experimental implementation https://github.com/gree/unity-webview/blob/38458bce76b16fb2ca286d34a606f4f35f2a5c6b/plugins/iOS/WebView.mm could solve the issue.

Thank you for your support. I will try it.
