### ISSUE TITLE
XCode cannot validate archive while preparing to upload to app store.

### ISSUE THREAD

**Issue by heha** [gree/unity-webview#66]
Your plugin is working fine on both android and ios. It's run smoothly on my iPad mini 1. However, when I tried to archive it, it showed me this:

> Archieve validatation failed due to the issues listed below.
> Unable to validate your application.
> The archive is invalid. /var/folders/hh/lq2dx5x57r5csdfb25sx25dr0000gn/T/XcodeDistPipeline.q24/Packages/Unity-iPhone.ipa does not exist.

I searched and found some workaround, which is go to Build Phases -> Copy Bundle Resources -> remove Webview.bundle and it's fixed. However, not not sure if it will effect the final app when it has been downloaded from store or not since it has been removed. Anybody know about this issue?

**Comment by KojiNakamaru** [comment]
`WebView.bundle` works only for Editor/OSX. On Unity Editor, You can select `WebView.bundle` to show the inspector and limit its target to Editor/OSX. I'll later place it under `Plugins/x86_64/` instead of `Plugins/` in `unity-webview.{unitypackage,zip}`.
![image](https://cloud.githubusercontent.com/assets/2645978/12905954/ee7d0d48-cf1e-11e5-839c-08a0e3e6bfc0.png)

**Comment by KojiNakamaru** [comment]
I've moved the plugin: https://github.com/gree/unity-webview/commit/b3dd5623de6047f35103ba568f8301406787f55b

**Comment by heha** [comment]
Thanks!
