### ISSUE TITLE
Can't open webpage that doens't have proper SSL Certificate.

### ISSUE THREAD

**Issue by cujo55575** [gree/unity-webview#758]
Hi, I am using this plugin to show a third party website.URL doesn't have an SSL certificate.So, it gives me “connection not secure” warning and doesn't show the webpage.URL does have “HTTPS” protocol though . Since I can’t force the website to fix their problem, is there a way for me to fix it from my end ? Thanks.

**Comment by KojiNakamaru** [comment]
You can enable http instead of https by:

* (for iOS) enabling "Allow downloads over HTTP (nonsecure)" in Project Settings.
* (for Android) defining `UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC` (cf. https://github.com/gree/unity-webview/tree/d3f2980193805b851e05f1e25c73a1c034f0084a#usescleartexttraffic ).
