### ISSUE TITLE
When Closing Webview UnityApp Sounds are not working on Android

### ISSUE THREAD

**Issue by ZeeshanAliTll** [gree/unity-webview#878]
Hello i am using webview in my game to play some videos it works fine on ios but on android it stops the background music and button sounds when i close the webview player the sounds are not resuming

**Comment by KojiNakamaru** [comment]
I modified the sample app to play a video in webview and play a sound with the `beep` button:

https://github.com/gree/unity-webview/tree/example-for-878

![image](https://user-images.githubusercontent.com/2645978/216093203-902f25f3-219f-4cb2-97ff-a6886b4f00e5.png)

This seems to work correctly on my devices (Vankyo S7 (Android 9), OSCAL Pad 8 (Android 11)). If I misunderstand anything, could you please provide a minimum app that reproduces your issue?

**Comment by ZeeshanAliTll** [comment]
Thank you for your reply. I mean that when i destroy webview my background music is not resuming. I will check your sample.

**Comment by KojiNakamaru** [comment]
Is the "background music" played by another app (such as Amazon Music)? It then seems a system-specific limitation, because the background music played by another app doesn't resume even for Chrome. I tried to utilize `requestAudioFocus()`/`abandonAudioFocus()` but could not succeed...

cf. https://developer.android.com/guide/topics/media-apps/audio-focus

**Comment by ZeeshanAliTll** [comment]
Thank you again for your reply your sample works fine for me i think there is problem with my app music.

**Comment by ZeeshanAliTll** [comment]
Thank you.
