### ISSUE TITLE
local webpage

### ISSUE THREAD

**Issue by jg78** [gree/unity-webview#9]
Is it possible to show a local webpage in unity-webview? I took the sample project and copied my webpage to Assets/StreamingAssets/www
then I changed SampleWebView.cs, invoking the webpage with

		string s = "jar:file://" + Application.dataPath + "!/assets/www/index.html";
		webViewObject.LoadURL(s);

in Start() - it is an example for Android.
The result is "Website not available". Am I missing something?

**Comment by quinnhoener** [comment]
Does anyone have this working yet? I've tried @jtothebell 's example, but wasn't sure where to add the "file:///android_asset/". I tried it in a bunch of places, but was unable to get this to work. I've successfully gotten online pages to load, but need to load an html file from the streaming assets folder. I get "Webpage not available".

**Comment by quinnhoener** [comment]
After more trial and error, I'm now getting a blank white screen instead of the "Webpage not available". I got to this point by extracting the file from Streaming Assets and saving it to the Persistent Data Path, then loading the page from there. References from these links:

http://forum.unity3d.com/threads/problem-loading-html-from-streamingassets-in-android.169535/
http://stackoverflow.com/questions/26822502/applicationdata-persistentdatapath-unity-editor-to-android
http://forum.unity3d.com/threads/unity-3d-android-sqlite-examples.114660/

I'm assuming at this point that this plugin doesn't work on Android for local web files. The blank white screen probably means it's finding the file, but is unable to display its contents. I'm not getting any errors from the Android log file.

**Comment by quinnhoener** [comment]
Finally got this working!

After you've copied the file to the Persistent Data Path, call 

webViewObject.LoadURL("file://" + Application.persistentDataPath + "/" + fileName);

The key being to add the "file://" at the beginning. Do this only for android and it should work for you. Here's the full example:

string fileName = "index.html";
string filepath = System.IO.Path.Combine(Application.streamingAssetsPath, fileName);
string storagePath = Application.persistentDataPath + "/" + fileName;

// Checks if it's an Android file in the jar. 
if (filepath.Contains("://")) 
{
	WWW www = new WWW(filepath);
	while (!www.isDone) {}
	
	if ( string.IsNullOrEmpty(www.error) )
	{
		System.IO.File.WriteAllBytes(storagePath, www.bytes);
	} // You should probably have an else here in case of an error. 
	// make sure you've created your webViewObject then,
        webViewObject.LoadURL(pagePath);
}
else
{
	// Everything else
	initWebView(filepath);
}
